program: train.py
method: bayes
metric: 
  name: loss
  goal: minimize
early_terminate:
  type: hyperband
parameters: 
  focalloss_alpha:
    min: 0.25
    max: 1
  focalloss_gamma:
    min: 1.0
    max: 2.0
  lr: 
    values: [5e-3, 1e-3, 5e-4, 1e-4, 5e-5, 1e-5]
  batch_size:
    